### ISSUE TITLE
jlibtorrent UnsatisfiedLinkError on Windows 10 64-bit

### ISSUE THREAD

**Issue by jvincent08** [tchoulihan/torrenttunes-client#13]
When running from the console we get:

/.torrenttunes-client/src/lib/x86/jlibtorrent.dll
Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
        at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:22)
        at com.frostwire.jlibtorrent.swig.libtorrentConstants.<clinit>(libtorrentConstants.java:12)
        at com.frostwire.jlibtorrent.LibTorrent.version(LibTorrent.java:16)
        at com.torrenttunes.client.LibtorrentEngine.<init>(LibtorrentEngine.java:120)
        at com.torrenttunes.client.LibtorrentEngine.<clinit>(LibtorrentEngine.java:96)
        at com.torrenttunes.client.db.Actions.updateLibtorrentSettings(Actions.java:123)
        at com.torrenttunes.client.Main.setupSettings(Main.java:95)
        at com.torrenttunes.client.Main.doMain(Main.java:71)
        at com.torrenttunes.client.Main.main(Main.java:128)

This is with the latest jre8u60

**Comment by tchoulihan** [comment]
Ah, I'm realizing that the build I was testing on was only 32-bit. I'll they can maven/gradle build me a 64 bit version as well.

**Comment by tchoulihan** [comment]
Could you try running:
`java -d32 -jar torrenttuneslauncher.jar`

If that works, I'll change this line for the windows versions.

**Comment by jvincent08** [comment]
That exact command didn't work with the 64 bit jre, but the program launches when using the 32 bit java.exe

**Comment by tchoulihan** [comment]
Damn. That's good to hear java 32-bit windows works though. Talking with the devs of jlibtorrent, they didn't seem too keen on working on a 64 bit jre windows version.

Because it doesn't seem to be on the radar, I'll close this out for now, but will potentially reopen it if there turns out to be a huge demand for it.

**Comment by tchoulihan** [comment]
Windows 64 bit support on the way.
